# Generated by Django 2.2.6 on 2019-10-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('value', models.FloatField()),
                ('value_type', models.CharField(choices=[('VALUE', 'Value'), ('PERCENT', 'Percent')], default='VALUE', max_length=8)),
                ('usage_remainder', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
    ]
